### ISSUE TITLE
JALR does not output expected result 

### ISSUE THREAD

**Issue by shibcreate** [pranjalchanda08/rv32i_ISA_emu#15]
When running: 

```asm
.align 2

.section .text
.globl _start

_start: 
    la t0, function
    jalr ra, 0(t0)

function:
    li t1, 0x12345
    ret

.section .data
 ```

I get the output

`x0: 0x00000000
  ra: 0x0000100c
  sp: 0x00000000
  gp: 0x00000000
  tp: 0x00000000
  t0: 0x0000100c
  t1: 0x00000000
  t2: 0x00000000
  s0: 0x00000000
  s1: 0x00000000
  a0: 0x00000000
  a1: 0x00000000
  a2: 0x00000000
  a3: 0x00000000
  a4: 0x00000000
  a5: 0x00000000
  a6: 0x00000000
  a7: 0x00000000
  s2: 0x00000000
  s3: 0x00000000
  s4: 0x00000000
  s5: 0x00000000
  s6: 0x00000000
  s7: 0x00000000
  s8: 0x00000000
  s9: 0x00000000
 s10: 0x00000000
 s11: 0x00000000
  t3: 0x00000000
  t4: 0x00000000
  t5: 0x00000000
  t6: 0x00000000
  pc: 0x00002014
`

I want to verify if this is user error / expected / bug

**Comment by pranjalchanda08** [comment]
Why do you suspect this as a bug?
`jalr rd, imm(rs1)` -> `rd = pc+4, pc = (rs1+imm i) & ~1`

**Comment by shibcreate** [comment]
The JALR does seem to have the correct output. But I wanted to understand why the function was not executed, resulting t1 to be 0x0.

**Comment by pranjalchanda08** [comment]
I am pushing a code change check #16

**Comment by pranjalchanda08** [comment]
The Return value was wrong for PC calculation. Please try and let me know if it works,

**Comment by shibcreate** [comment]
Understood. Will check right now.
