### ISSUE TITLE
Bug: Store instruction issues

### ISSUE THREAD

**Issue by shibcreate** [pranjalchanda08/rv32i_ISA_emu#27]
```asm
    .align 4
    .section .text
    .globl _start

_start:
    li a0, 0x13
    li a1, 0x23
    add a2, a0, a1
    sb a0, 0(a4)
    lbu t0, 0(a4)
    sh a1, 2(a4)
    lhu t1, 2(a4)
    sw a2, 4(a4)
    lw t2, 4(a4)

.section .data
a4: 
    .space 16
```

The instructions for sb, sh, sw - would this be the proper validation method for testing? The result of this gave me: 

  x0: 0x00000000
  ra: 0x00000000
  sp: 0x00000000
  gp: 0x00000000
  tp: 0x00000000
  t0: 0x0000000a
  t1: 0x0000000b
  t2: 0xffffff0c
  s0: 0x00000000
  s1: 0x00000000
  a0: 0x00000013
  a1: 0x00000023
  a2: 0x00000036
  a3: 0x00000000
  a4: 0x00000000
  a5: 0x00000000
  a6: 0x00000000
  a7: 0x00000000
  s2: 0x00000000
  s3: 0x00000000
  s4: 0x00000000
  s5: 0x00000000
  s6: 0x00000000
  s7: 0x00000000
  s8: 0x00000000
  s9: 0x00000000
 s10: 0x00000000
 s11: 0x00000000
  t3: 0x00000000
  t4: 0x00000000
  t5: 0x00000000
  t6: 0x00000000
  pc: 0x00001024

**Comment by pranjalchanda08** [comment]
can you please change the data section name `a4:` to something else as `a4` represents a register alias. then see the behavior.

**Comment by pranjalchanda08** [comment]
I Tried the following with a minor store execution fix.

```asm
    .align 4
    .section .text
    .globl _start

_start:
    la a4, _data    # Load address of the store
    li a0, 0x13     # Load value to store in a0
    sb a0, 1(a4)    # Store byte at address pointed by a4

.section .data
_data:
    .space 16
```
```sh
$ grep -v "0x00000000" ./out/str/reg_dump.txt 
x10 <a0>: 0x00000013
x14 <a4>: 0x00002000
pc: 0x00001010
```
The following was the hexdump output of the above:
```sh
$ hexdump out/str/ram_dump.bin 
0000000 0000 0000 0000 0000 0000 0000 0000 0000
*
0001000 1717 0000 0713 0007 0513 0130 00a3 00a7
0001010 0000 0000 0000 0000 0000 0000 0000 0000
*
0002000 1300 0000 0000 0000 0000 0000 0000 0000                               Store at 0x2000 space: val -> 0x13
0002010 0000 0000 0000 0000 0000 0000 0000 0000
*
0004000
```

**Comment by shibcreate** [comment]
Understood. Thanks for the clarification!
