### ISSUE TITLE
Makefile revamping; Fixing the issues pointed in Release 0.1

### ISSUE THREAD

**Issue by pranjalchanda08** [pranjalchanda08/rv32i_ISA_emu#33]
![image](https://github.com/user-attachments/assets/270bb9ea-c73a-4233-a116-c13c8bfb2444)
![image](https://github.com/user-attachments/assets/acb92241-de51-48d4-b846-6509d67a14d2)
![image](https://github.com/user-attachments/assets/9da4522c-d19f-4852-afe9-9f35a0d46fb5)
![image](https://github.com/user-attachments/assets/5ff6764d-af4f-4c29-b849-ca09bdb6609c)

**Comment by Tabrez-dev** [comment]
I will try to work on this

**Comment by pranjalchanda08** [comment]
> I will try to work on this

Get online with @akashkollipara to understand the changes and do it accordingly

**Comment by Tabrez-dev** [comment]
I have messaged Akash on discord, in the mean time i ran the codespace in github codespaces but i get this error. 


@Tabrez-dev ➜ /workspaces/slash-sim (dev) $ sudo apt install gcc-riscv64-unknown-elf build-essential make
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package gcc-riscv64-unknown-elf
@Tabrez-dev ➜ /workspaces/slash-sim (dev) $ 

edit: i ran these two commands: sudo add-apt-repository ppa:ubuntu-toolchain-r/test
sudo apt update
and then i ran sudo apt install gcc-riscv64-linux-gnu
now its working
